# Generated by Django 5.0.1 on 2024-02-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blogpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippets',
            field=models.CharField(default='View more', max_length=100),
        ),
    ]
