# Generated by Django 5.0.1 on 2024-02-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogpost_snippets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='snippets',
            field=models.CharField(max_length=100),
        ),
    ]
