# Generated by Django 5.0.1 on 2024-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blogpost_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
